version: '3'

volumes:
  vendor:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/handlers:/go/src/handlers
      - vendor:/go/src/api/vendor
    ports:
      - 3001:3001
    tty:
      true